version: '3.7'
services:
  postgres:
    container_name: posgres
    image: postgres:10.7-alpine
    restart: always
    environment:
      POSTGRES_DB: assesment
    ports:
      - 5432:5432
    command: postgres -c 'max_connections=50'
  redis:
    container_name: redis
    image: redis:6.0.9-alpine
    restart: always
    ports:
      - 6379:6379
